accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path("password/change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("password/change/done/", views.PasswordChangeDoneView.as_view(), name="password_change_done", ),
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done", ),
    path("reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm", ),
    path("reset/done/", views.PasswordResetCompleteView.as_view(), name="password_reset_complete", ),
    # path("settings/users/update/<int:pk>", views.UserUpdateWithAdmin.as_view(), name='user_update_admin'),
    # path("settings/users/delete/<int:pk>", views.UserDeleteView.as_view(), name='user_delete'),
    # path("users/update/<int:pk>", views.UserUpdate.as_view(), name='user_update'),
    # path("users/create/", views.UserCreate.as_view(), name='user_create'),
    # path("users/", views.UsersList.as_view(), name='users_list'),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('login/', views.LoginView.as_view(), name='login'),
    path("", views.DashboardView.as_view(), name="dashboard"),
]

config/urls.py
"""
URL configuration for config project.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings


urlpatterns = [
    path('main_panel_admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('pages.urls', namespace='pages')),
]

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    *urlpatterns,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    phone_number = PhoneNumberField(blank=False, unique=True)

    def get_fullname(self):
        return super().get_full_name()

    get_fullname.short_description = "Name"

    def __str__(self):
        return self.get_fullname() + f'({self.username})'

    def get_absolute_url(self):
        return reverse('accounts:dashboard')

pages/models.py
from django.db import models

# Create your models here.

preferences/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'phone_number', 'password1', 'password2']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = UserChangeForm.Meta.fields
        exclude = ['user', 'groups', 'user_permissions']
        widgets = {
            'username': forms.TextInput(
                attrs={'type': 'text', 'class': 'form-control'}
            ),
            'email': forms.TextInput(
                attrs={'type': 'email', 'class': 'form-control'}
            ),
            'phone_number': forms.TextInput(
                attrs={'type': 'phone', 'class': 'form-control'}
            ),
        }

accounts/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic


class DashboardView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'accounts/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class LoginView(auth_views.LoginView):
    template_name = 'accounts/login.html'


class LogoutView(auth_views.LogoutView):
    pass


class PasswordChangeView(auth_views.PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy("accounts:password_change_done")


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = "accounts/password_change_done.html"


class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    email_template_name = 'accounts/password_reset_email.html'
    success_url = reverse_lazy("accounts:password_reset_done")


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = "accounts/password_reset_done.html"


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy("accounts:password_reset_complete")
    template_name = "accounts/password_reset_confirm.html"


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'pages/home_page.html'


class AboutPageView(TemplateView):
    template_name = 'pages/about_page.html'


class ContactPageView(TemplateView):
    template_name = 'pages/contact_page.html'

preferences/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/index.html
{% extends 'admin_panel/index.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block main %}

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'admin_panel/login.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
    {% translate "Login Page" %}
{% endblock %}

{% block main %}
    {% bootstrap_messages %}
    <div class="login-area login-s2">
        <div class="container">
            <div class="login-box ptb--100">
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="login-form-head">
                        <h4>{% trans 'Login Page' %}</h4>
                        <p>{% trans 'Hello there, Sign in and start managing your Admin Template' %}</p>
                    </div>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="row mb-4 rmber-area">
                        <div class="col-6">
                            <div class="custom-control custom-checkbox mr-sm-2">
                                <input type="checkbox" class="custom-control-input" id="customControlAutosizing">
                                <label class="custom-control-label" for="customControlAutosizing">
                                    {% trans 'Remember Me' %}
                                </label>
                            </div>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{% url 'accounts:password_reset' %}">{% trans 'Forgot Password?' %}</a>
                        </div>
                    </div>
                    <div class="submit-btn-area">
                        <button id="form_submit" type="submit">{% trans 'Submit' %} <i class="ti-arrow-right"></i></button>
                    </div>
                    <div class="submit-btn-area mt-3">
                        <a href="{% url 'pages:home' %}">{% trans 'Back to Home' %}</a>
                    </div>
                    <div class="form-footer text-center mt-2">
                        <p class="text-muted">{% trans "Don't have an account?" %} <a href="#">{% trans 'Sign up' %}</a></p>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'admin_panel/login.html' %}
{% load i18n %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
    {% translate "Password reset" %}
{% endblock %}

{% block main %}
    {% bootstrap_messages %}
    <div class="login-area login-s2">
        <div class="container">
            <div class="login-box ptb--100">
                <form>
                    <div class="login-form-head" style="text-align: justify;">
                        <h4>{% translate "Password reset" %}</h4>
                        <p>{% translate "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

                        <p>{% translate "If you don't receive an email, please make sure you’ve entered the address you registered with, and check your spam folder." %}</p>
                    </div>
                    {% csrf_token %}
                    <div class="submit-btn-area">
                        <a href="{% url 'accounts:login' %}" id="form_submit">{% translate "Back to login" %}</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends 'admin_panel/login.html' %}
{% load i18n %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
    {% translate "Change Password" %}
{% endblock %}

{% block main %}
    {% bootstrap_messages %}
    <div class="login-area login-s2">
        <div class="container">
            <div class="login-box ptb--100">
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="login-form-head">
                        <h4>{% translate "Change Password" %}</h4>
                        <p>{% translate "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>
                    </div>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="row mb-4 rmber-area">
                        <div class="col-12 text-right">
                            <a href="{% url 'accounts:dashboard' %}">{% translate "Back to Dashboard" %}</a>
                        </div>
                    </div>
                    <div class="submit-btn-area">
                        <button id="form_submit" type="submit">{% translate "Submit" %} <i class="ti-arrow-right"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'admin_panel/login.html' %}
{% load i18n %}

{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
    {% translate "Password reset" %}
{% endblock %}

{% block main %}
    {% bootstrap_messages %}
    <div class="login-area login-s2">
        <div class="container">
            <div class="login-box ptb--100">
                <form>
                    <div class="login-form-head" style="text-align: justify;">
                        <h4>{% translate "Password reset" %}</h4>
                        <p>{% translate "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

                        <p>{% translate "If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder." %}</p>
                    </div>
                    {% csrf_token %}
                    <div class="submit-btn-area">
                        <a href="{% url 'accounts:login' %}" id="form_submit">{% translate "Back to login" %}</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'admin_panel/login.html' %}
{% load i18n %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
    {% translate "Reset Password" %}
{% endblock %}

{% block main %}
    {% bootstrap_messages %}
    <div class="login-area login-s2">
        <div class="container">
            <div class="login-box ptb--100">
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="login-form-head">
                        <h4>{% translate "Reset Password" %}</h4>
                        <p>{% translate "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>
                    </div>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="row mb-4 rmber-area">
                        <div class="col-12 text-right">
                            <a href="{% url 'accounts:login' %}">{% translate "Back to login" %}</a>
                        </div>
                    </div>
                    <div class="submit-btn-area">
                        <button id="form_submit" type="submit">{% translate "Submit" %} <i class="ti-arrow-right"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'admin_panel/login.html' %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% load i18n %}

{% block title %}
    {% translate 'Password reset' %}
{% endblock %}

{% block main %}
    {% bootstrap_messages %}
    <div class="login-area login-s2">
        <div class="container">
            <div class="login-box ptb--100">
                <form>
                    <div class="login-form-head" style="text-align: justify;">
                        <h4>{% translate 'Password reset' %}</h4>
                        <p>{% translate "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>
                        <p>{% translate "If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder." %}</p>
                    </div>
                    {% csrf_token %}
                    <div class="submit-btn-area">
                        <a href="{% url 'accounts:login' %}" id="form_submit">{% translate "Back to login" %}</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}
{% autoescape off %}
    {% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

    {% translate "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

    {% translate "Thanks for using our site!" %}

    {% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends 'admin_panel/login.html' %}
{% load i18n %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
    {% trans 'Reset Password' %}
{% endblock %}

{% block main %}
    {% bootstrap_messages %}
    <div class="login-area login-s2">
        <div class="container">
            <div class="login-box ptb--100">
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="login-form-head">
                        <h4>{% trans 'Reset Password' %}</h4>
                        <p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>
                    </div>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="row mb-4 rmber-area">
                        <div class="col-12 text-right">
                            <a href="{% url 'accounts:login' %}">{% trans "Back to login" %}</a>
                        </div>
                    </div>
                    <div class="submit-btn-area">
                        <button id="form_submit" type="submit">{% trans "Submit" %} <i class="ti-arrow-right"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

base/templates/admin_panel/footer.html
{% load i18n %}
<footer>
    <div class="footer-area">
        <p>© Copyright 2018. All right reserved. Template by <a href="https://colorlib.com/wp/">Colorlib</a>.</p>
    </div>
</footer>

base/templates/admin_panel/header_area.html
{% load static %}
{% load i18n %}
{% load local_data %}
{% language as pages_language %}
<div class="header-area">
    <div class="row align-items-center">
        <!-- nav and search button -->
        <div class="col-md-6 col-sm-8 clearfix">
            <div class="nav-btn pull-left">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="search-box pull-left">
                <form action="#">
                    <input type="text" name="search" placeholder="{% translate 'Search...' %}" required>
                    <i class="ti-search"></i>
                </form>
            </div>
        </div>
        <!-- profile info & task notification -->
        <div class="col-md-6 col-sm-4 clearfix">
            <ul class="notification-area pull-right">
                <li id="full-view"><i class="ti-fullscreen"></i></li>
                <li id="full-view-exit"><i class="ti-zoom-out"></i></li>
                <li class="dropdown">
                    <i class="ti-bell dropdown-toggle" data-toggle="dropdown">
                        <span>2</span>
                    </i>
                    <div class="dropdown-menu bell-notify-box notify-box">
                                    <span class="notify-title">You have 3 new notifications <a
                                            href="#">view all</a></span>
                        <div class="nofity-list">
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                <div class="notify-text">
                                    <p>You have Changed Your Password</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-comments-smiley btn-info"></i></div>
                                <div class="notify-text">
                                    <p>New Commetns On Post</p>
                                    <span>30 Seconds ago</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-primary"></i></div>
                                <div class="notify-text">
                                    <p>Some special like you</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-comments-smiley btn-info"></i></div>
                                <div class="notify-text">
                                    <p>New Commetns On Post</p>
                                    <span>30 Seconds ago</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-primary"></i></div>
                                <div class="notify-text">
                                    <p>Some special like you</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                <div class="notify-text">
                                    <p>You have Changed Your Password</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                <div class="notify-text">
                                    <p>You have Changed Your Password</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>
                <li class="dropdown">
                    <i class="fa fa-envelope-o dropdown-toggle" data-toggle="dropdown"><span>3</span></i>
                    <div class="dropdown-menu notify-box nt-enveloper-box">
                                    <span class="notify-title">
                                        You have 3 new notifications
                                        <a href="#">view all</a></span>
                        <div class="nofity-list">
                            <a href="#" class="notify-item">
                                <div class="notify-thumb">
                                    <img src="{% static 'admin_panel/images/author/author-img1.jpg' %}" alt="image">
                                </div>
                                <div class="notify-text">
                                    <p>Aglae Mayer</p>
                                    <span class="msg">Hey I am waiting for you...</span>
                                    <span>3:15 PM</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb">
                                    <img src="{% static 'admin_panel/images/author/author-img2.jpg' %}" alt="image">
                                </div>
                                <div class="notify-text">
                                    <p>Aglae Mayer</p>
                                    <span class="msg">When you can connect with me...</span>
                                    <span>3:15 PM</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb">
                                    <img src="{% static 'admin_panel/images/author/author-img3.jpg' %}" alt="image">
                                </div>
                                <div class="notify-text">
                                    <p>Aglae Mayer</p>
                                    <span class="msg">I missed you so much...</span>
                                    <span>3:15 PM</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>
                <li class="settings-btn">
                    <i class="ti-settings"></i>
                </li>
            </ul>
        </div>
    </div>
</div>

base/templates/admin_panel/pages_title_area.html
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Dashboard</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="index.html">Home</a></li>
                    <li><span>Dashboard</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="assets/images/author/avatar.png" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">Kumkum Rai <i
                        class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Message</a>
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>

base/templates/admin_panel/preloader.html
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->
<!-- preloader area start -->
<div id="preloader">
    <div class="loader"></div>
</div>
<!-- preloader area end -->

base/templates/admin_panel/sidebar.html
{% load static %}

<div class="sidebar-menu">
    <div class="sidebar-header">
        <div class="logo">
            <a href="index.html"><img src="{% static 'admin_panel/images/icon/logo.png' %}" alt="logo"></a>
        </div>
    </div>
    <div class="main-menu">
        <div class="menu-inner">
            <nav>
                <ul class="metismenu" id="menu">
                    <li class="active">
                        <a href="javascript:void(0)" aria-expanded="true"><i
                                class="ti-dashboard"></i><span>dashboard</span></a>
                        <ul class="collapse">
                            <li class="active"><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
                            <li><a href="index2.html">Ecommerce dashboard</a></li>
                            <li><a href="index3.html">SEO dashboard</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0)" aria-expanded="true"><i class="ti-layout-sidebar-left"></i>
                            <span>
                                Account
                            </span>
                        </a>
                        <ul class="collapse">
                            <li><a href="{% url 'accounts:password_change' %}">Change Password</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> <span>Logout</span></a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

base/templates/base/footer.html
{% load i18n %}
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url 'pages:home' %}" class="nav-link px-2 text-muted">
                {% trans 'Home' %}
            </a></li>
            <li class="nav-item"><a href="{% url 'pages:about' %}" class="nav-link px-2 text-muted">
                {% trans 'About' %}
            </a></li>
            <li class="nav-item"><a href="{% url 'pages:contact' %}" class="nav-link px-2 text-muted">
                {% trans 'Contact' %}
            </a></li>
        </ul>
        <p class="text-center text-muted">{% trans '© 2021 Company, Inc' %}</p>
    </footer>
</div>

base/templates/base/header.html
{% load i18n %}
{% load local_data %}
{% language as page_language %}

<header class="container">
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
                <title>Bootstrap</title>
                <path fill-rule="evenodd" clip-rule="evenodd"
                      d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                      fill="currentColor"></path>
            </svg>
            <span class="fs-4">{% trans 'Company Name' %}</span>
        </a>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'pages:home' %}">
                {% trans 'Home' %}
            </a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'pages:about' %}">
                {% trans 'About' %}
            </a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'pages:contact' %}">
                {% trans 'Contact' %}
            </a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'accounts:login' %}">
                {% trans 'Login' %}
            </a>
            <a class="me-3 py-2 text-dark text-decoration-none">
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <select name="language" id="language" onchange="this.form.submit()">
                        {% if page_language == 'fa' %}
                            <option value="fa">{% trans 'Persian' %}</option>
                            <option value="en">{% trans 'English' %}</option>
                        {% else %}
                            <option value="en">{% trans 'English' %}</option>
                            <option value="fa">{% trans 'Persian' %}</option>
                        {% endif %}
                    </select>
                </form>
            </a>
        </nav>
    </div>
</header>